# [LAB-04] 지도학습-분류모델 | 01-프로젝트 개요

## #01. 준비작업

### 1. 라이브러리 참조

In [1]:
from hossam import load_data
from helpers import *
import numpy as np

from pandas import crosstab, pivot_table

📦 아이티윌 이광호 강사가 제작한 라이브러리를 사용중입니다.
📚 자세한 사용 방법은 https://py.hossam.kr 을 참고하세요.
📧 Email: leekh4232@gmail.com
🎬 Youtube: https://www.youtube.com/@hossam-codingclub
📝 Blog: https://blog.hossam.kr/
🔖 Version: 0.5.33

### 2. 데이터 불러오기

In [2]:
origin = load_data("titanic")
origin.head()

📚 타이타닉호 침몰은 역사상 가장 악명 높은 난파 사고 중 하나입니다. 1912년 4월 15일, 첫 항해 중이던 타이타닉호는 빙산과 충돌하여 침몰했습니다. 당시 배에는 모든 승객과 승무원을 태울 수 있는 구명보트가 충분하지 않아 2,224명의 승객과 승무원 중 1,502명이 목숨을 잃었습니다. 생존에는 어느 정도 운이 작용했지만, 일부 집단은 다른 집단보다 생존 가능성이 더 높았던 것으로 보입니다. 이번 과제에서는 승객 데이터(예: 이름, 나이, 성별, 사회경제적 계층 등)를 사용하여 `어떤 유형의 사람들이 생존할 가능성이 더 높았을까?`라는 질문에 답하는 예측 모델을 구축해야 합니다. (출처: https://www.kaggle.com/datasets/yasserh/titanic-dataset)

변수명       설명
-----------  -------------------------------------------------------
PassengerId  탑승객의 ID(인덱스와 같은 개념)
Survived     생존유무(0은 사망 1은 생존)
Pclass       객실의 등급(1=1등급, 2=2등급, 3=3등급)
Name         이름
Sex          성별
SibSp        동승한 형제 혹은 배우자의 수
Parch        동승한 자녀 혹은 부모의 수
Ticket       티켓번호
Fare         요금
Cabin        선실
Embarked     탑승지 (C = Cherbourg, Q = Queenstown, S = Southampton)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000,1,0,A/5 21171,7.250,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.000,1,0,PC 17599,71.283,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000,0,0,STON/O2. 3101282,7.925,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000,1,0,113803,53.100,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000,0,0,373450,8.050,NaN,S

타이타닉호 침몰은 역사상 가장 악명 높은 난파 사고 중 하나입니다.  
1912년 4월 15일, 첫 항해 중이던 타이타닉호는 빙산과 충돌하여 침몰했습니다.

이 데이터는 탑승객의 생존 여부와 관련된 대표적인 분류 문제입니다.

- PassengerId: 탑승객 ID
- Survived: 생존여부 (0=사망, 1=생존)
- Pclass: 객실 등급 (1=1등급, 2=2등급, 3=3등급)
- Name: 이름
- Sex: 성별
- SibSp: 동승한 형제 혹은 배우자의 수
- Parch: 동승한 자녀 혹은 부모의 수
- Ticket: 티켓번호
- Fare: 요금
- Cabin: 선실
- Embarked: 탑승지 (C = Cherbourg, Q = Queenstown, S = Southampton)

## #02. 데이터 품질 점검

### 1. 자료형 확인

In [3]:
origin.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     1309 non-null   int64
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   str
 4   Sex          1309 non-null   str
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Cabin        295 non-null    str
 11  Embarked     1307 non-null   str
dtypes: float64(2), int64(5), object(1), str(4)
memory usage: 166.2+ KB

### 2. 데이터 중복 점검

In [4]:
df1 = my_qtcheck.check_duplications(origin, drop=True)
df1.head()

중복된 행의 수: 0

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000,1,0,A/5 21171,7.250,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.000,1,0,PC 17599,71.283,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000,0,0,STON/O2. 3101282,7.925,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000,1,0,113803,53.100,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000,0,0,373450,8.050,NaN,S

### 3. 데이터 타입 점검

- `Survived`, `Pclass`, `Sex`, `Embarked` 를 명목형(category)으로 변환한다.
- `Pclass`는 1·2·3이라는 숫자로 저장되어 있지만 “3등급은 1등급의 3배”가 아니므로 연속형으로 두면 안 된다.

In [5]:
df2 = my_qtcheck.set_type(
    df1,
    as_category=["Survived", "Pclass", "Sex", "Embarked"]
)

df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     1309 non-null   category
 2   Pclass       1309 non-null   category
 3   Name         1309 non-null   str
 4   Sex          1309 non-null   category
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Cabin        295 non-null    str
 11  Embarked     1307 non-null   category
dtypes: category(4), float64(2), int64(3), object(1), str(2)
memory usage: 123.1+ KB
<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     1309 non-null   category
 2   Pclass       1309 non-null   category
 3   Name         1309 non-null   str
 4   Sex          1309 non-null   category
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Cabin        295 non-null    str
 11  Embarked     1307 non-null   category
dtypes: category(4), float64(2), int64(3), object(1), str(2)
memory usage: 123.1+ KB

### 4. 결측치 점검

In [6]:
my_qtcheck.check_missing_values(df2)

             Missing Count  Missing Ratio(%)
PassengerId              0             0.000
Survived                 0             0.000
Pclass                   0             0.000
Name                     0             0.000
Sex                      0             0.000
Age                    263            20.092
SibSp                    0             0.000
Parch                    0             0.000
Ticket                   0             0.000
Fare                     1             0.076
Cabin                 1014            77.464
Embarked                 2             0.153

### 5. 결측치 처리

In [7]:
df3 = df2.dropna(subset=["Fare", "Embarked"])

# Fare와 Embarked 결측치가 모두 처리되었는지 확인
my_qtcheck.check_missing_values(df3)

             Missing Count  Missing Ratio(%)
PassengerId              0             0.000
Survived                 0             0.000
Pclass                   0             0.000
Name                     0             0.000
Sex                      0             0.000
Age                    263            20.138
SibSp                    0             0.000
Parch                    0             0.000
Ticket                   0             0.000
Fare                     0             0.000
Cabin                 1013            77.565
Embarked                 0             0.000

## #03. 파생변수 생성

### 1. 객실 유무

In [8]:
df4 = df3.copy()

# Cabin 컬럼이 결측치가 아닌 경우 객실있음, 결측치인 경우 객실 없음으로 파생변수 생성
df4["HasCabin"] = df4["Cabin"].notnull()

# Cabin 컬럼은 결측치가 많으므로 제거
df4.drop(columns=["Cabin"], inplace=True)

# HasCabin 컬럼을 category 타입으로 변환
df4 = my_qtcheck.set_type(df4, as_category=["HasCabin"])

df4.head()

<class 'pandas.DataFrame'>
Index: 1306 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1306 non-null   int64
 1   Survived     1306 non-null   category
 2   Pclass       1306 non-null   category
 3   Name         1306 non-null   str
 4   Sex          1306 non-null   category
 5   Age          1043 non-null   float64
 6   SibSp        1306 non-null   int64
 7   Parch        1306 non-null   int64
 8   Ticket       1306 non-null   object
 9   Fare         1306 non-null   float64
 10  Embarked     1306 non-null   category
 11  HasCabin     1306 non-null   category
dtypes: category(5), float64(2), int64(3), object(1), str(1)
memory usage: 122.9+ KB

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,HasCabin
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000,1,0,A/5 21171,7.250,S,False
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.000,1,0,PC 17599,71.283,C,True
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000,0,0,STON/O2. 3101282,7.925,S,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000,1,0,113803,53.100,S,True
4,5,0,3,"Allen, Mr. William Henry",male,35.000,0,0,373450,8.050,S,False

### 2. 동승 가족 수 계산

In [9]:
df5 = df4.copy()

# 새로운 파생 변수 생성 (동승 가족 수 = 동승한 형제·배우자 수 + 동승한 부모·자녀 수 + 본인)
df5["FamilySize"] = df5["SibSp"] + df5["Parch"] + 1

# 결과 확인
df5.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,HasCabin,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000,1,0,A/5 21171,7.250,S,False,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.000,1,0,PC 17599,71.283,C,True,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000,0,0,STON/O2. 3101282,7.925,S,False,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000,1,0,113803,53.100,S,True,2
4,5,0,3,"Allen, Mr. William Henry",male,35.000,0,0,373450,8.050,S,False,1

### 3. 신분 파생변수 추가 (1) - 이름에서 호칭 분리

In [10]:
# 이름에서 호칭 추출 : "성, 호칭. 이름" 형식이므로 쉼표와 마침표 사이를 뽑는다
title_raw = df5["Name"].str.extract(r',\s*([^\.]+)\.', expand=False)
title_raw = title_raw.str.strip()

title_raw.value_counts().rename("빈도").to_frame().T

Name,Mr,Miss,Mrs,Master,Rev,Dr,Col,Ms,Major,Mlle,Don,Mme,Lady,Sir,Capt,the Countess,Jonkheer,Dona
빈도,756,259,196,61,8,8,4,2,2,2,1,1,1,1,1,1,1,1

### 4. 신분 파생변수 추가 (2) - 의미별 호칭 정의

In [11]:
title_map = {
    # 성인 남성
    "Mr": "Mr", "Don": "Mr", "Sir": "Mr", "Jonkheer": "Mr",

    # 미혼 여성
    "Miss": "Miss", "Mlle": "Miss", "Ms": "Miss",

    # 기혼 여성
    "Mrs": "Mrs", "Mme": "Mrs", "Dona": "Mrs",
    "Lady": "Mrs", "the Countess": "Mrs",

    # 남자아이
    "Master": "Master",

    # 전문직·군인·성직자
    "Dr": "Officer", "Rev": "Officer", "Col": "Officer",
    "Major": "Officer", "Capt": "Officer",
}

title_map

{'Mr': 'Mr',
 'Don': 'Mr',
 'Sir': 'Mr',
 'Jonkheer': 'Mr',
 'Miss': 'Miss',
 'Mlle': 'Miss',
 'Ms': 'Miss',
 'Mrs': 'Mrs',
 'Mme': 'Mrs',
 'Dona': 'Mrs',
 'Lady': 'Mrs',
 'the Countess': 'Mrs',
 'Master': 'Master',
 'Dr': 'Officer',
 'Rev': 'Officer',
 'Col': 'Officer',
 'Major': 'Officer',
 'Capt': 'Officer'}

### 5. 신분 파생변수 추가 (3) - 호칭 파생변수 추가 (신분을 의미)

In [12]:
df6 = df5.copy()

# Title 변수 추가
df6["Title"] = title_raw.map(title_map)

# 매핑 누락 점검
print("Title 매핑 누락 :", df6["Title"].isna().sum(), "건\n")

# 문자열이므로 명목형으로 선언
df6 = my_qtcheck.set_type(df6, as_category=["Title"])

# 이름 컬럼 제거
df6 = df6.drop(columns=["Name"])

df6.head()

Title 매핑 누락 : 0 건

<class 'pandas.DataFrame'>
Index: 1306 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1306 non-null   int64
 1   Survived     1306 non-null   category
 2   Pclass       1306 non-null   category
 3   Name         1306 non-null   str
 4   Sex          1306 non-null   category
 5   Age          1043 non-null   float64
 6   SibSp        1306 non-null   int64
 7   Parch        1306 non-null   int64
 8   Ticket       1306 non-null   object
 9   Fare         1306 non-null   float64
 10  Embarked     1306 non-null   category
 11  HasCabin     1306 non-null   category
 12  FamilySize   1306 non-null   int64
 13  Title        1306 non-null   category
dtypes: category(6), float64(2), int64(4), object(1), str(1)
memory usage: 134.4+ KB

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,HasCabin,FamilySize,Title
0,1,0,3,male,22.000,1,0,A/5 21171,7.250,S,False,2,Mr
1,2,1,1,female,38.000,1,0,PC 17599,71.283,C,True,2,Mrs
2,3,1,3,female,26.000,0,0,STON/O2. 3101282,7.925,S,False,1,Miss
3,4,1,1,female,35.000,1,0,113803,53.100,S,True,2,Mrs
4,5,0,3,male,35.000,0,0,373450,8.050,S,False,1,Mr

### 6. 생성된 신분 파생 변수의 분포 확인

In [13]:
# 신분에 따른 성별 분포
display(crosstab(df6["Title"], df6["Sex"]))

# 신분에 따른 나이 분포 피벗 테이블
display(
    pivot_table(
        df6,
        index="Title",
        values="Age",
        aggfunc=["count", "median", "min", "max"],
        observed=False,
    )
)

Sex      female  male
Title
Master        0    61
Miss        263     0
Mr            0   759
Mrs         200     0
Officer       1    22

        count median    min    max
          Age    Age    Age    Age
Title
Master     53  4.000  0.330 14.500
Miss      212 22.000  0.170 63.000
Mr        583 29.000 11.000 80.000
Mrs       173 35.000 14.000 76.000
Officer    22 49.500 23.000 70.000

## #04. 나이 변수에 대한 결측치 처리

### 1. 신분별로 결측치 대체 기준 세우기

In [14]:
# 신분별 나이 분포 요약
age_stats = df6.groupby("Title", observed=True)["Age"].agg(
    인원="size",
    결측=lambda s: s.isna().sum(),
    mean="mean",
    median="median",
    skew="skew",
)

# 대체값 판단 규칙 : |왜도| <= 0.5 -> 평균, 그 밖에는 중앙값
age_stats["대체기준"] = (
    age_stats["skew"].abs() <= 0.5
).map({True: "mean", False: "median"})

# 대체값
age_stats["대체값"] = np.where(
    age_stats["대체기준"] == "mean",
    age_stats["mean"],
    age_stats["median"]
)

age_stats

          인원   결측   mean  median   skew    대체기준    대체값
Title
Master    61    8  5.483   4.000  0.466    mean  5.483
Miss     263   51 21.748  22.000  0.412    mean 21.748
Mr       759  176 32.256  29.000  1.017  median 29.000
Mrs      200   27 36.827  35.000  0.390    mean 36.827
Officer   23    1 46.273  49.500 -0.405    mean 46.273

### 2. 나이 결측치 처리

In [15]:
df7 = df6.copy()

# 신분(Title)별로 결측 Age를 집단별 대표값으로 대체
for title in age_stats.index:
    mask = df7["Age"].isna() & (df7["Title"] == title)
    df7.loc[mask, "Age"] = age_stats.loc[title, "대체값"]

my_qtcheck.check_missing_values(df7)

             Missing Count  Missing Ratio(%)
PassengerId              0             0.000
Survived                 0             0.000
Pclass                   0             0.000
Sex                      0             0.000
Age                      0             0.000
SibSp                    0             0.000
Parch                    0             0.000
Ticket                   0             0.000
Fare                     0             0.000
Embarked                 0             0.000
HasCabin                 0             0.000
FamilySize               0             0.000
Title                    0             0.000

## #05. 데이터 셋 정리

### 1. 불필요한 변수 제거

- `PassengerId`는 탑승객의 일련번호이므로 제거한다.
- `Ticket`은 문자열이고 관측치마다 다른 값을 갖기 때문에 분석에 활용하기 어려워 제거한다.
- `SibSp`, `Parch`는 파생변수 `FamilySize`에 사용되었으므로 정보가 중복되어 제거한다.
- `Sex`는 `Title`에 성별 정보가 포함되어 있으므로 제거한다.

In [16]:
df8 = df7.drop(
    columns=["PassengerId", "Ticket", "SibSp", "Parch", "Sex"]
)

# 데이터셋 저장
df8.to_excel("titanic_qtcheck.xlsx", index=False)

df8.head()

  Survived Pclass    Age   Fare Embarked HasCabin  FamilySize Title
0        0      3 22.000  7.250        S    False           2    Mr
1        1      1 38.000 71.283        C     True           2   Mrs
2        1      3 26.000  7.925        S    False           1  Miss
3        1      1 35.000 53.100        S     True           2   Mrs
4        0      3 35.000  8.050        S    False           1    Mr

## #06. 기술통계량 확인

### 1. 명목형 변수의 기술 통계량

In [17]:
cat_desc = my_qtcheck.categorical_summary(
    df8,
    value_counts=False,
    save_path="titanic_categorical_summary.xlsx"
)

cat_desc

        Survived  Pclass Embarked HasCabin Title
count       1306    1306     1306     1306  1306
unique         2       3        3        2     5
top            0       3        S    False    Mr
freq         814     708      913     1013   759

### 2. 연속형 변수의 기술 통계량

여기서 생성한 기술 통계량 표가 단변량 분석에서 활용되기 때문에, 여기서는 인사이트 발굴 없이 통계량 표만 확인하고 넘어간다.

In [18]:
num_desc = my_qtcheck.numerical_summary(
    df8,
    save_path="titanic_numerical_summary.xlsx"
)

num_desc

,count,mean,std,min,25%,50%,75%,max,rel_diff,rdiff_flag,iqr,upper_bound,lower_bound,upper_outliers,upper_outliers_ratio,lower_outliers,lower_outliers_ratio,outliers,outliers_ratio,skew,skew_interpret,kurt,kurt_interpret,log_need
Age,1306.000,29.397,13.119,0.170,21.748,29.000,36.000,80.000,0.014,similar,14.252,57.378,0.370,47,0.036,2,0.002,49,0.038,0.478,symmetric,0.766,leptokurtic,none
Fare,1306.000,33.224,51.766,0.000,7.896,14.454,31.275,512.329,1.299,large_diff,23.379,66.344,-27.173,169,0.129,0,0.000,169,0.129,4.376,right tail,27.080,leptokurtic,log1p
FamilySize,1306.000,1.886,1.585,1.000,1.000,1.000,2.000,11.000,0.886,large_diff,1.000,3.500,-0.500,125,0.096,0,0.000,125,0.096,2.849,right tail,10.273,leptokurtic,log